/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva_passagens_completo;

import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Silva
 */
public class JF_telacadastro extends javax.swing.JFrame {  
     Arquivo arq= new Arquivo();
      String nome_arquivo= "banco_cadastro.txt";
      String test=Arquivo.Read(nome_arquivo);
      int cont1=0,i=0,j;
   
    
    

    /**
     * Creates new form JF_telacadastro
     */
    public JF_telacadastro() {
        initComponents();
        setSize(790,500);
        setLocationRelativeTo(null);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campo_nome = new javax.swing.JTextField();
        campo_cartao = new javax.swing.JTextField();
        campo_idade = new javax.swing.JTextField();
        campo_senha = new javax.swing.JTextField();
        btn_gocadastro = new javax.swing.JButton();
        campo_cpf = new javax.swing.JFormattedTextField();
        campo_telefone = new javax.swing.JFormattedTextField();
        btn_voltar_telacadastro = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        campo_nome.setBackground(new java.awt.Color(153, 153, 153));
        campo_nome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campo_nome.setForeground(new java.awt.Color(255, 255, 255));
        campo_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(campo_nome);
        campo_nome.setBounds(130, 110, 310, 30);

        campo_cartao.setBackground(new java.awt.Color(153, 153, 153));
        campo_cartao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campo_cartao.setForeground(new java.awt.Color(255, 255, 255));
        campo_cartao.setMargin(new java.awt.Insets(2, 2, 6, 2));
        campo_cartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cartaoActionPerformed(evt);
            }
        });
        getContentPane().add(campo_cartao);
        campo_cartao.setBounds(158, 234, 280, 30);

        campo_idade.setBackground(new java.awt.Color(153, 153, 153));
        campo_idade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campo_idade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(campo_idade);
        campo_idade.setBounds(674, 94, 90, 30);

        campo_senha.setBackground(new java.awt.Color(153, 153, 153));
        campo_senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campo_senha.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(campo_senha);
        campo_senha.setBounds(158, 352, 280, 30);

        btn_gocadastro.setBackground(new java.awt.Color(255, 0, 0));
        btn_gocadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_gocadastro.setForeground(new java.awt.Color(255, 255, 255));
        btn_gocadastro.setText("CADASTRAR");
        btn_gocadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gocadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gocadastro);
        btn_gocadastro.setBounds(640, 350, 130, 40);

        campo_cpf.setBackground(new java.awt.Color(153, 153, 153));
        campo_cpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            campo_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_cpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(campo_cpf);
        campo_cpf.setBounds(130, 170, 310, 30);

        campo_telefone.setBackground(new java.awt.Color(153, 153, 153));
        campo_telefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            campo_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campo_telefone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(campo_telefone);
        campo_telefone.setBounds(160, 293, 280, 30);

        btn_voltar_telacadastro.setBackground(new java.awt.Color(102, 102, 102));
        btn_voltar_telacadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar_telacadastro.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar_telacadastro.setText("VOLTAR");
        btn_voltar_telacadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_telacadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_telacadastro);
        btn_voltar_telacadastro.setBounds(540, 350, 90, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserva_passagens_completo/CAPA_2.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 24, 790, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gocadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gocadastroActionPerformed
                  boolean ok=true;
                
                    if (Cadastro.getPessoas().size()>0){
                           for (i=0;i<Cadastro.getPessoas().size();i++)
                           {
                              if(Cadastro.getPessoas().get(i).getCpf().equals(campo_cpf.getText()))
                             {
                                     ok=false;
                                     i=Cadastro.getPessoas().size();
                                     JOptionPane.showMessageDialog(null,"ERRO!ESTE CPF JÁ ESTÁ CADASTRADO");  
                                     
                             }
                             
                           }
                   }
                    if(ok) {  
                    
                         arq.Write(nome_arquivo,campo_nome.getText(),campo_cpf.getText(),
                        campo_cartao.getText(),campo_telefone.getText(),campo_idade.getText()
                        ,campo_senha.getText());
                         
                         JOptionPane.showMessageDialog(null,"NOME: "+ campo_nome.getText()+ 
                         " CPF: "+ campo_cpf.getText()+ " ,CADASTRADO COM SUCESSO");
                    }
                    
                     while (!test.split(";")[cont1].equals("&") && !test.equals("&;") && test.isEmpty()==false){
                    Cadastro p= new Cadastro();
                     p.setNome( test.split(";")[cont1]);
                     cont1++;
                     
                     p.setCpf(test.split(";")[cont1]);
                     cont1++;
                     

                     p.setCartaocredito(test.split(";")[cont1]);
                     cont1++;

                     p.setTel(test.split(";")[cont1]);
                     cont1++;

                     p.setIdade(test.split(";")[cont1]);
                     cont1++;
                     
                     p.setSenha(test.split(";")[cont1]);
                     cont1++;
                     
                     p.adiciona(p);
                     
        }
      for(i=0; i<Cadastro.getPessoas().size();i++){
        System.out.println(Cadastro.getPessoas().get(i).getNome()+"|"+
                     Cadastro.getPessoas().get(i).getCpf()+"|"+Cadastro.getPessoas().get(i).getCartaocredito()+"|"+
                     Cadastro.getPessoas().get(i).getTel()+"|"+Cadastro.getPessoas().get(i).getIdade()+"|"+
                     Cadastro.getPessoas().get(i).getSenha());        
                     
    }

                  
    }//GEN-LAST:event_btn_gocadastroActionPerformed

    private void campo_cartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cartaoActionPerformed

    private void campo_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nomeActionPerformed

    private void btn_voltar_telacadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_telacadastroActionPerformed
        Interface inter= new Interface();
        inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltar_telacadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_telacadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_telacadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_telacadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_telacadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_telacadastro().setVisible(true);
            }
        });
        
      
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_gocadastro;
    private javax.swing.JButton btn_voltar_telacadastro;
    private javax.swing.JTextField campo_cartao;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JTextField campo_idade;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_senha;
    private javax.swing.JFormattedTextField campo_telefone;
    // End of variables declaration//GEN-END:variables
}
