/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva_passagens_completo;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Silva
 */
public class JF_telalogin extends javax.swing.JFrame {
    
      Interface inter2 = new Interface();
        Arquivo arq= new Arquivo();
       String nome_arquivo1= "voos.txt";
      String test1=Arquivo.Read(nome_arquivo1);
      int cont1=0,cont2=0,i=0,j;
    
    
     
      

    /**
     * Creates new form JF_telalogin
     */
    public JF_telalogin() {
        initComponents();
        setSize(790,500);
        setLocationRelativeTo(null);
            while (!test1.split(";")[cont2].equals("&") && !test1.equals("&;") && test1.isEmpty()==false){
                    Voo_Reservado v= new Voo_Reservado();
                     v.setNome(test1.split(";")[cont2]);
                     cont2++;
                     v.setPoltrona(test1.split(";")[cont2]);
                     cont2++;
                     v.setClasse(test1.split(";")[cont2]);
                     cont2++;
                     v.setData(test1.split(";")[cont2]);
                     cont2++;
                     v.setHora(test1.split(";")[cont2]);
                     cont2++;
                     v.setOrigem(test1.split(";")[cont2]);
                     cont2++;
                     v.setDestino(test1.split(";")[cont2]);
                     cont2++;
                     
                     v.adiciona(v);
        }
               for(i=0; i<Voo_Reservado.voos.size();i++){
        System.out.println("NOME: "+ Voo_Reservado.voos.get(i).getNome()+"| POLTRONA: "+ Voo_Reservado.voos.get(i).getPoltrona()+
                "| CLASSE: "+Voo_Reservado.voos.get(i).getClasse()+"| DATA: "+
                Voo_Reservado.voos.get(i).getData()+"| HORA: "+Voo_Reservado.voos.get(i).getHora()+"| ORIGEM: "+
                Voo_Reservado.voos.get(i).getOrigem()+"| DESTINO:"+Voo_Reservado.voos.get(i).getDestino());        
                     
    }
     
    
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_senha_telalogin = new javax.swing.JPasswordField();
        botaoentrar_telalogin = new javax.swing.JButton();
        lbl_cpf_telalogin = new javax.swing.JFormattedTextField();
        btn_voltar_telalogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SENHA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 210, 80, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 160, 50, 30);

        lbl_senha_telalogin.setBackground(new java.awt.Color(153, 153, 153));
        lbl_senha_telalogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_senha_telalogin.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_senha_telalogin);
        lbl_senha_telalogin.setBounds(290, 210, 220, 30);

        botaoentrar_telalogin.setBackground(new java.awt.Color(255, 51, 0));
        botaoentrar_telalogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoentrar_telalogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoentrar_telalogin.setText("ENTRAR");
        botaoentrar_telalogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoentrar_telalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoentrar_telaloginActionPerformed(evt);
            }
        });
        getContentPane().add(botaoentrar_telalogin);
        botaoentrar_telalogin.setBounds(350, 250, 100, 40);

        lbl_cpf_telalogin.setBackground(new java.awt.Color(153, 153, 153));
        lbl_cpf_telalogin.setForeground(new java.awt.Color(255, 255, 255));
        try {
            lbl_cpf_telalogin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        lbl_cpf_telalogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cpf_telalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_cpf_telaloginActionPerformed(evt);
            }
        });
        getContentPane().add(lbl_cpf_telalogin);
        lbl_cpf_telalogin.setBounds(290, 160, 220, 30);

        btn_voltar_telalogin.setBackground(new java.awt.Color(102, 102, 102));
        btn_voltar_telalogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_voltar_telalogin.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar_telalogin.setText("voltar");
        btn_voltar_telalogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar_telalogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_telaloginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_telalogin);
        btn_voltar_telalogin.setBounds(360, 320, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserva_passagens_completo/CAPA3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 20, 770, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoentrar_telaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoentrar_telaloginActionPerformed
        JF_telalogin_sucess obj3= new JF_telalogin_sucess();
        
        int i,achou=0;
        if(Cadastro.getPessoas().size()>0){ 
            
            for(i=0; i<Cadastro.getPessoas().size();i++){
                if(Cadastro.getPessoas().get(i).getSenha().equals(lbl_senha_telalogin.getText())&& Cadastro.getPessoas().get(i).getCpf().equals(lbl_cpf_telalogin.getText())){
                    obj3.setVisible(true);
                     obj3.recebeNome(Cadastro.getPessoas().get(i).getNome());
                     obj3.recebeCpf(Cadastro.getPessoas().get(i).getCpf());
                     dispose();
                     achou=1;
                     i=Cadastro.getPessoas().size();
                }
            }
            if(achou==0){
                JOptionPane.showMessageDialog(null, "ERRO! Usuário ou senha inválidos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ainda não há cadastros registrados!");
        }
        
            
    }//GEN-LAST:event_botaoentrar_telaloginActionPerformed

    private void lbl_cpf_telaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_cpf_telaloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_cpf_telaloginActionPerformed

    private void btn_voltar_telaloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_telaloginActionPerformed

        inter2.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_voltar_telaloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_telalogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_telalogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoentrar_telalogin;
    private javax.swing.JButton btn_voltar_telalogin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField lbl_cpf_telalogin;
    private javax.swing.JPasswordField lbl_senha_telalogin;
    // End of variables declaration//GEN-END:variables
}
