/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reserva_passagens_completo;

/**
 *
 * @author Carlos Silva
 */
public class JF_tela_reservar extends javax.swing.JFrame {
 
    /**
     * Creates new form JF_tela_reservar
     */
    public JF_tela_reservar() {
        initComponents();
        setSize(810,500);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_classeEconomica = new javax.swing.JButton();
        btn_classeA = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        recebe_cpf = new javax.swing.JLabel();
        lbl_recebenome_cliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_classeEconomica.setBackground(new java.awt.Color(255, 51, 0));
        btn_classeEconomica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_classeEconomica.setForeground(new java.awt.Color(255, 255, 255));
        btn_classeEconomica.setText("QUERO ECONOMIZAR");
        btn_classeEconomica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_classeEconomicaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_classeEconomica);
        btn_classeEconomica.setBounds(510, 190, 210, 40);

        btn_classeA.setBackground(new java.awt.Color(255, 51, 0));
        btn_classeA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_classeA.setForeground(new java.awt.Color(255, 255, 255));
        btn_classeA.setText("QUERO CLASSE A");
        btn_classeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_classeAActionPerformed(evt);
            }
        });
        getContentPane().add(btn_classeA);
        btn_classeA.setBounds(80, 190, 190, 40);

        btn_voltar.setBackground(new java.awt.Color(255, 51, 0));
        btn_voltar.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltar.setText("VOLTAR");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar);
        btn_voltar.setBounds(360, 260, 100, 23);

        recebe_cpf.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        recebe_cpf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(recebe_cpf);
        recebe_cpf.setBounds(730, 360, 140, 20);

        lbl_recebenome_cliente.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_recebenome_cliente);
        lbl_recebenome_cliente.setBounds(200, 110, 180, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reserva_passagens_completo/CAPA_RESERVAR.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 30, 800, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_classeEconomicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_classeEconomicaActionPerformed
        Poltronas_reservar_economica pol2= new Poltronas_reservar_economica();
        pol2.setVisible(true);
        pol2.setResizable(false);
        pol2.recebeNome(lbl_recebenome_cliente.getText());
        pol2.recebeCpf(recebe_cpf.getText());
        dispose();
    }//GEN-LAST:event_btn_classeEconomicaActionPerformed

    private void btn_classeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_classeAActionPerformed
       Poltronas_Reservar pol= new Poltronas_Reservar();
       pol.setVisible(true);
       pol.recebeNome(lbl_recebenome_cliente.getText());
       pol.recebeCpf(recebe_cpf.getText());
       pol.setResizable(false);
       dispose();
    }//GEN-LAST:event_btn_classeAActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        JF_telalogin_sucess volt= new JF_telalogin_sucess();
        volt.setVisible(true);
        volt.recebeNome(lbl_recebenome_cliente.getText());
        volt.recebeCpf(recebe_cpf.getText());
        dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_tela_reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_tela_reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_tela_reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_tela_reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_tela_reservar().setVisible(true);
            }
        });
        
    }
     public void recebeNome(String nome){
        lbl_recebenome_cliente.setText(nome);
    }
    public void recebeCpf(String cpf){
        recebe_cpf.setText(cpf);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_classeA;
    private javax.swing.JButton btn_classeEconomica;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_recebenome_cliente;
    private javax.swing.JLabel recebe_cpf;
    // End of variables declaration//GEN-END:variables
}
